Feature(Issue #5) : Join an existing shopping list to allow list collaboration
the-collab-lab/tcl-11-smart-shopping-list pull request #31
Opened 2020-08-22 23:49 UTC by daredtech

## Description

This pull request allows the user to join the existing shopping list by providing the token associated with this list. If there is no such list in the database, an error would be displayed, allowing the user to re-enter the token or create a new list. Moreover, previously accessed lists would be displayed so the user could pick which one they want to modify. 

- Retired the `List` and `Add Item` links from the `Footer` component. 
- Added `Lists` component that would store and render all the available tokens. Clicking on a token would take you to the list associated with it, display the items in a current list, and allow the user to add new items. 
- Added `Footer` component to the `List` component and `Add Item` component that allows the user to go on the main page and change the active list. When the user clicks `Create a new shopping list` or `Join an existing list` buttons, the token gets saved to the local storage with the corresponding key.  

## Related Issue

Closes #5

## Acceptance Criteria

- [X]  When the user does not already have a token in localStorage, on the onboarding/home screen, a simple form is displayed that allows the user to enter a token
- [X]  Entering the token and hitting submit saves the token to localStorage, effectively giving them joint control of the list
- [X]  On submit, show an error if the token does not exist
- [X]  If they get an error message, allow them to try again or create a new list

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓  | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![image](https://user-images.githubusercontent.com/6282435/90967680-d8267f00-e4b0-11ea-8e53-2bea9dd5abed.png)

### After

![image](https://user-images.githubusercontent.com/6282435/90967665-add4c180-e4b0-11ea-8c89-1a92d981ac51.png)

## Testing Steps / QA Criteria

- From your terminal, run `git checkout bl-vh-join-and-share-shopping-list`.
- Once on the `bl-vh-join-and-share-shopping-list` branch, run `npm start` to load the browser.
- Enter the existing token `andes casey mew` and click `Join an existing list` button to join the list. Select the token name from `Available Lists` and click on it. This would take you to the chosen list and display the items in it. Once done adding items, click `Home` to select a different list or create a new one.
- Enter non-existing token `i don't exist` and click `Join an existing list` button to join the list. An alert would be displayed saying `Sorry, this collection doesn't exist. Please try again or create a new list`.

2020-08-23 00:03 UTC, jendevelops commented on src/components/CustomButton/CustomButton.component.jsx
> +const CustomButton = ({ children, ...otherProps }) => (
Noice use of destructuring 👍👍👍👍👍👍👍👍

2020-08-23 00:07 UTC, jendevelops commented on src/components/Home/Home.component.jsx
> +      );
Javascript alert messages are not the most accessible option when displaying an error.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/alerts#Checking_for_validity_and_notifying_the_user_2

Maybe displaying errors is something we can discuss during the Weekly Sync about how to approach it in a different way. @joeylaguna

2020-08-23 00:10 UTC, jendevelops commented on src/components/Home/Home.component.jsx
> +        }`}
Love the use of template literals scattered throughout your code! Efficient!

2020-08-23 00:21 UTC, joeylaguna commented on src/components/Home/Home.component.jsx
> +  // To
Can we add something to this comment or remove it?

2020-08-23 00:22 UTC, jendevelops commented on src/components/Home/Home.component.jsx
> +  // To
Beat me to it! 😅

2020-08-23 00:22 UTC, joeylaguna commented on src/components/Lists/Lists.style.scss
> +.lists {
Always been a fan of having a separate CSS file 😄

2020-08-23 00:23 UTC, joeylaguna commented on src/components/Home/Home.component.jsx
> +  const joinExistingList = async () => {
Great use of async/await here!

2020-08-23 00:44 UTC, jendevelops commented on src/components/Home/Home.component.jsx
> -    console.log('called generate token');
Is this console log necessary?

2020-08-23 00:48 UTC, jendevelops requested changes
I pulled down the branch and attempted to connect to a share token that's on firebase, but I was not redirected to the shopping list. @daredtech @brewswain Do you have any idea what the issue could be?

Another thing I noticed is that clicking join an existing list generates a new token locally, but I don't see a new collection being generated on the Firebase side.

![Screenshot from 2020-08-22 17-46-04](https://user-images.githubusercontent.com/52062192/90968290-7f9ab600-e49f-11ea-9c05-f8d9e1e62454.png)

You can see all the tokens I generated locally, but they're not present in Firebase

![Screenshot from 2020-08-22 17-47-38](https://user-images.githubusercontent.com/52062192/90968308-a1943880-e49f-11ea-9519-bf257b5d11b0.png)

2020-08-23 01:00 UTC, daredtech commented
Good catch, @jendevelops ! Seems like we have an issue with Available Lists in `Lists` component. Right now, it displays all the keys available in one's localStorage. However, instead, it should check them against the database and only display the ones that exist in the database. We are going to fix that. 

`Join an existing list` is not intended to generate a new collection in the database. On the contrary, it checks whether there is a collection associated with the token entered and only then saves it your local storage so one would have access to it. Only `Create a New Shopping List` generates a new token and updates the collection in the database

2020-08-23 01:05 UTC, brewswain commented on src/components/Home/Home.component.jsx
> +  // To
Oops 😳
I'll send a commit now

2020-08-23 01:32 UTC, jendevelops commented
Thanks for the reply @daredtech @brewswain 

I also had issues when creating a new token. It would generate a new token locally, but I would not see a new token in firebase. Are y'all able to recreate that issue?

2020-08-23 17:03 UTC, CodeMeKathy commented
Overall, great contributions and styling @brewswain and @daredtech!

@jendevelops, when I create a shopping list (token: berg aztec jew) but do not add an item to the list, I experience something similar. 

![image](https://user-images.githubusercontent.com/32943879/90984051-980edd00-e540-11ea-9841-3eee1ff90db1.png)

![image](https://user-images.githubusercontent.com/32943879/90984057-a6f58f80-e540-11ea-98a7-3a0c661aabf7.png)


> Thanks for the reply @daredtech @brewswain
> 
> I also had issues when creating a new token. It would generate a new token locally, but I would not see a new token in firebase. Are y'all able to recreate that issue?

2020-08-23 17:03 UTC, CodeMeKathy approved these changes

2020-08-23 17:49 UTC, jendevelops commented
@CodeMeKathy Ah, I see that is the issue. If that's the case that makes sense. Don't want to clutter up firbase too much with empty lists.

2020-08-23 18:30 UTC, daredtech commented
@CodeMeKathy @jendevelops That is an inherited functionality. Firestore gets updated only when there is at least one item added to the associated list/token. Otherwise, it could get populated with a bunch of empty lists. We could discuss it more during our call today and come up with an ultimate implementation.

2020-08-23 22:32 UTC, jendevelops commented
@brewswain @daredtech After the weekly sync today, I have a much better idea of what you were trying to go for in terms of functionality. A couple of points I wanted to bring up:

1. If we let the user input a token and it gets stored in local storage, but the list is synced with Firebase until an item is added, what will happen if someone ends up typing in the same token, and starts using the list? Or what happens if person 2 generates a new list that has the same token, and down the line person 1 tries to add items to that list as well?

2. Regarding usability: it was not entirely clear to me that joining a list would not automatically take me to that list. It would be nice if joining a list either:
  - adds to the available lists and there's a button that says "go to list"
  - redirects you straight to the list

Other than those two points, really great job with the idea to add the Available Lists section to the home page. Love it!

2020-08-24 00:52 UTC, stef-codes requested changes
- I was unable to see the lists. I tried with an incognito browser and with my existing browser that has an existing token. 
- They key and the values seem to be mixed in local storage (This could be a mismatch from the implementation in another issue.)

This is an example with multiple tokens: 

<img width="1289" alt="Screen Shot 2020-08-23 at 5 41 06 PM" src="https://user-images.githubusercontent.com/54756529/90993077-4bd79300-e568-11ea-8e2a-1e2bc3769891.png">

2020-08-25 18:04 UTC, brewswain commented on src/components/Home/Home.component.jsx
> -    console.log('called generate token');
Oh yeah we removed it cause we didn't think it was needed!

2020-08-25 18:18 UTC, brewswain commented
> * I was unable to see the lists. I tried with an incognito browser and with my existing browser that has an existing token.
> * They key and the values seem to be mixed in local storage (This could be a mismatch from the implementation in another issue.)
> 
> This is an example with multiple tokens:
> 
> <img alt="Screen Shot 2020-08-23 at 5 41 06 PM" width="1289" src="https://user-images.githubusercontent.com/54756529/90993077-4bd79300-e568-11ea-8e2a-1e2bc3769891.png">

Hey stefanie, this is cause there's a bit of a restructuring going on, so you def won't see any lists right now :(

2020-08-27 01:33 UTC, daredtech commented
@jendevelops 

1. At the current state, everyone with the same token would have access to the same list. Let's assume the initial list had 'coffee, creamer' when user1 opened it. User1 wants to add 'oat milk' and gets distracted. Meanwhile, user2 adds 'ice' to the list. The moment the firebase gets updated with 'ice', the list would re-render to display the change for everyone who uses the same token.  The updated list would be 'coffee, creamer, ice'. In the future, we could add a password, so only authorized people could share the list. Moreover, we could ensure that all the tokens are unique. But it is outside of this issue.
2. We could change the button to `Add token` and add a description something like 'click on the token associated with a list you want to edit' or something. Would that be acceptable?
Thanks.

2020-08-27 03:19 UTC, daredtech commented
Fixed token validation. 
Only tokens that exist in the database would get displayed now. 
Added a note about clicking on a token.

2020-08-30 04:11 UTC, merged